(()=>{
const fmtMoney=(n)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
const hhmm=s=>s?String(s).slice(11,16):'—';
const labels={best_deal:'🏆 BEST DEAL',good_value:'🪙 GOOD VALUE',cheap_of_week:'💸 CHEAP OF THE WEEK'};
const why={best_deal:'Le meilleur mix prix + horaires + temps réellement utile.',good_value:'Le meilleur budget global parmi les week-ends qui gardent au moins ~44 h utiles.',cheap_of_week:'Le billet direct le moins cher du radar.'};
function css(){const s=document.createElement('style');s.textContent=`
.deal-scout{margin:24px 0 34px;padding:20px;background:#173f32;color:#fff}.deal-scout h2{margin:0 0 6px;font-family:Georgia,serif;font-size:30px}.deal-scout>p{margin:0 0 16px;color:#dfe9e4;max-width:760px}.deal-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.deal-card{background:#fff;color:#26231e;padding:15px;border-top:6px solid #f0c24a}.deal-card h3{margin:0 0 8px;font-size:13px;letter-spacing:.04em}.deal-city{font:900 25px Georgia,serif;color:#173f32}.deal-vibe{font-size:12px;color:#6e6558;margin:4px 0 10px}.deal-price{font-weight:950;font-size:20px}.deal-route{font-size:12px;font-weight:800;line-height:1.45;margin-top:8px}.deal-stats{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}.deal-stat{background:#eef3ef;padding:5px 7px;font-size:11px;font-weight:900}.deal-why{font-size:11px;color:#6e6558;margin-top:9px;line-height:1.4}.deal-note{font-size:10px;color:#cbd8d1;margin-top:12px}.deal-empty{padding:12px;background:#fff;color:#6e6558}@media(max-width:780px){.deal-grid{grid-template-columns:1fr}.deal-scout h2{font-size:26px}}
`;document.head.appendChild(s)}
function card(p,key){if(!p)return'';const o=p.outbound||{},r=p.return||{};return `<article class="deal-card"><h3>${labels[key]}</h3><div class="deal-city">${p.name}</div><div class="deal-vibe">${p.vibe||''}</div><div class="deal-price">${fmtMoney(p.flightPrice)} <small>vols directs A+R</small></div><div class="deal-route">Ven. ${o.from||'?'} ${hhmm(o.departure)} → ${o.to||'?'} ${hhmm(o.arrival)} · ${o.carrier||''}<br>Dim. ${r.from||'?'} ${hhmm(r.departure)} → ${r.to||'?'} ${hhmm(r.arrival)} · ${r.carrier||''}</div><div class="deal-stats"><span class="deal-stat">≈ ${Math.round(p.usefulHours)} h utiles</span><span class="deal-stat">week-end estimé ≈ ${fmtMoney(p.estimatedWeekend)}</span></div><div class="deal-why">${why[key]}</div></article>`}
function distinctPicks(candidates){if(!candidates?.length)return{};const sorted=[...candidates];const cheap=[...sorted].sort((a,b)=>a.flightPrice-b.flightPrice||b.usefulHours-a.usefulHours)[0];const remain=sorted.filter(x=>x.id!==cheap.id);const valuePool=remain.filter(x=>x.usefulHours>=44);const good=[...(valuePool.length?valuePool:remain)].sort((a,b)=>a.estimatedWeekend-b.estimatedWeekend||b.usefulHours-a.usefulHours)[0];const remain2=remain.filter(x=>!good||x.id!==good.id);const best=[...remain2].sort((a,b)=>a.valueScore-b.valueScore||b.usefulHours-a.usefulHours)[0];return{cheap_of_week:cheap,good_value:good,best_deal:best}}
async function run(){css();const anchor=document.querySelector('#destinations');if(!anchor)return;const wrap=document.createElement('section');wrap.id='deals';wrap.innerHTML=`<div class="w"><div class="deal-scout"><h2>Les bons plans qui peuvent renverser le vote</h2><p>Liverpool, Belgrade ou Valence deviennent trop chers ? Le radar regarde aussi d’autres villes en direct sur les mêmes dates et sort trois gagnantes différentes selon le prix, la valeur globale et le vrai temps de week-end.</p><div class="deal-grid" id="dealGrid"><div class="deal-empty">Recherche des deals en cours…</div></div><div class="deal-note">Radar limité aux vols directs Paris → destination, vendredi 23 → dimanche 25 octobre. Actualisé avec le même snapshot que les autres vols.</div></div></div>`;anchor.parentNode.insertBefore(wrap,anchor);
try{const r=await fetch(`flights-live.json?ts=${Date.now()}`,{cache:'no-store'});const d=await r.json();const candidates=d.dealScout?.candidates||[];const picks=distinctPicks(candidates);const html=['best_deal','good_value','cheap_of_week'].map(k=>card(picks[k],k)).join('');document.querySelector('#dealGrid').innerHTML=html||'<div class="deal-empty">Pas encore de deal direct fiable remonté. Le prochain refresh retente automatiquement.</div>';}catch(e){document.querySelector('#dealGrid').innerHTML='<div class="deal-empty">Radar temporairement indisponible.</div>';}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(run,120));else setTimeout(run,120);
})();