(()=>{
const CAP=200;
const INFO={
krakow:{stay:{hotel:[105,125],food:[120,140],extras:[30,40]},transfer:'KRK → centre : train ≈ 20 min',currency:'PLN',area:'Kazimierz',weather:'≈ 7–12 °C',pain:'🟡 Un petit effort',note:'Beauvais peut allonger le départ de Paris.'},
dublin:{stay:{hotel:[170,210],food:[145,175],extras:[35,45]},transfer:'DUB → centre : bus/taxi ≈ 30–45 min',currency:'€',area:'Smithfield / Stoneybatter',weather:'≈ 9–13 °C',pain:'🟡 Un petit effort',note:'Retour à protéger à cause du marathon du dimanche.'},
bologna:{stay:{hotel:[130,150],food:[125,145],extras:[30,40]},transfer:'BLQ → centre : Marconi Express ≈ 7 min + marche',currency:'€',area:'Quadrilatero / Pratello',weather:'≈ 11–18 °C',pain:'🟢 Facile',note:'Centre compact : très peu de temps perdu une fois arrivé.'},
tirana:{transportEstimate:[120,190],stay:{hotel:[90,110],food:[95,115],extras:[25,35]},transfer:'TIA → centre : navette/taxi ≈ 30–40 min',currency:'ALL',area:'Blloku',weather:'≈ 14–22 °C',pain:'🟡 Un petit effort',note:'Prix et horaires exacts du direct encore à verrouiller.'},
vienna:{transportEstimate:[150,200],stay:{hotel:[145,170],food:[135,155],extras:[35,45]},transfer:'VIE → centre : Railjet/S-Bahn ≈ 15–25 min',currency:'€',area:'Neubau / MuseumsQuartier',weather:'≈ 8–15 °C',pain:'🟢 Facile',note:'Très bonne logistique si le direct reste sous 200 €.'},
rotterdam:{transportEstimate:[100,180],stay:{hotel:[155,180],food:[140,160],extras:[35,45]},transfer:'Arrivée directement à Rotterdam Centraal',currency:'€',area:'Witte de With / Markthal',weather:'≈ 9–14 °C',pain:'🟢 Facile',note:'Pas d’aéroport : gros avantage sur un week-end de 48 h.'},
bucharest:{transportEstimate:[160,200],stay:{hotel:[95,115],food:[105,125],extras:[25,35]},transfer:'OTP → centre : train/bus/taxi ≈ 25–45 min',currency:'RON',area:'Universitate / Old Town',weather:'≈ 9–17 °C',pain:'🟡 Un petit effort',note:'Bon rapport coût/sorties si le direct est confirmé.'},
munich:{transportEstimate:[170,200],stay:{hotel:[150,175],food:[140,160],extras:[35,45]},transfer:'MUC → centre : S-Bahn ≈ 40–45 min',currency:'€',area:'Altstadt / Glockenbach',weather:'≈ 7–14 °C',pain:'🟡 Un petit effort',note:'Aéroport assez loin ; pas d’Oktoberfest à ces dates.'},
turin:{transportEstimate:[150,200],stay:{hotel:[125,150],food:[120,140],extras:[30,40]},transfer:'Selon option : Porta Susa en train ou TRN → centre ≈ 30–45 min',currency:'€',area:'Quadrilatero Romano',weather:'≈ 10–17 °C',pain:'🟡 Un petit effort',note:'Le bon couple prix/horaires reste à verrouiller.'},
amsterdam:{transportEstimate:[120,190],stay:{hotel:[180,215],food:[145,170],extras:[35,45]},transfer:'Arrivée directement à Amsterdam Centraal',currency:'€',area:'Jordaan / De Pijp',weather:'≈ 9–14 °C',pain:'🟢 Facile',note:'Le train fait gagner énormément de temps, l’hôtel reste cher.'},
malaga:{stay:{hotel:[120,145],food:[120,140],extras:[30,40]},transfer:'AGP → centre : Cercanías ≈ 12 min',currency:'€',area:'Centro Histórico',weather:'≈ 18–24 °C',pain:'🟡 Un petit effort',note:'Très simple sur place, mais les horaires actuels réduisent le week-end.'},
alicante:{stay:{hotel:[110,135],food:[115,135],extras:[30,40]},transfer:'ALC → centre : bus C6 ≈ 20–30 min',currency:'€',area:'Centro / El Barrio',weather:'≈ 18–24 °C',pain:'🟢 Facile',note:'Bonne logistique si les vols restent bien placés.'}
};
const fmt=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
const range=r=>`${fmt(r[0])}–${fmt(r[1])}`;
const hh=s=>s?String(s).slice(11,16):'—';
const add=(a,b)=>[a[0]+b[0],a[1]+b[1]];
const add3=(a,b,c)=>[a[0]+b[0]+c[0],a[1]+b[1]+c[1]];
function liveFor(data,id){const c=data?.cities?.[id];const o=c?.options?.find(x=>x.kind==='recommended')||c?.options?.[0];if(o)return o;const d=(data?.dealScout?.candidates||[]).find(x=>x.id===id);if(d)return {price:d.flightPrice,usefulHours:d.usefulHours,outbound:d.outbound,return:d.return,centerArrival:d.centerArrival,leaveCenter:d.leaveCenter};return null}
function travelBlock(id,cfg,live){const price=live?.price!=null?fmt(live.price):(cfg.transportEstimate?`≈ ${fmt(Math.round((cfg.transportEstimate[0]+cfg.transportEstimate[1])/2/5)*5)}`:'À confirmer');const out=live?.outbound;const back=live?.return;const center=live?.centerArrival?hh(live.centerArrival):'à confirmer';const leave=live?.leaveCenter?hh(live.leaveCenter):'à confirmer';const useful=live?.usefulHours!=null?`≈ ${Math.round(live.usefulHours)} h`:'à confirmer';return `<section class="retro-travel"><h4>✈️ Le voyage en vrai</h4><p class="retro-intro">Quand on pose les sacs vendredi, et quand on doit réellement quitter le centre dimanche.</p><div class="retro-grid"><div><small>ALLER</small><b>${out?`${out.from} ${hh(out.departure)} → ${out.to} ${hh(out.arrival)}`:'Horaire exact à confirmer'}</b></div><div><small>DANS LE CENTRE</small><b>${center}</b><span>${cfg.transfer}</span></div><div><small>RETOUR</small><b>${back?`${back.from} ${hh(back.departure)} → ${back.to} ${hh(back.arrival)}`:'Horaire exact à confirmer'}</b></div><div><small>QUITTER LE CENTRE DIMANCHE</small><b>${leave}</b></div><div><small>TEMPS UTILE SUR PLACE</small><b>${useful}</b></div><div><small>PRIX TRANSPORT</small><b>${price}</b><span>${live?'Prix vérifié sur les dates':'Prix estimatif'}</span></div></div><div class="retro-note">${cfg.note}</div></section>`}
function budgetBlock(cfg,live){const tr=live?.price!=null?[live.price,live.price]:cfg.transportEstimate||[0,0];const s=cfg.stay;const stay=add3(s.hotel,s.food,s.extras);const total=add(tr,stay);return `<section class="retro-budget"><h4>💸 Budget estimatif / personne</h4><div class="budget-row"><span>Transport A/R</span><b>${live?.price!=null?fmt(live.price):range(tr)}</b></div><div class="budget-row"><span>2 nuits</span><b>${range(s.hotel)}</b></div><div class="budget-row"><span>Repas + bars</span><b>${range(s.food)}</b></div><div class="budget-row"><span>Local + activités</span><b>${range(s.extras)}</b></div><div class="budget-row total"><span>TOTAL réaliste</span><b>${range(total)}</b></div><p>Hypothèse de sélection pour environ 6 personnes. Ce n’est pas un devis : on reverrouille hôtel et transport avant achat.</p></section>`}
function practicalBlock(cfg){return `<section class="retro-practical"><h4>🧭 Infos pratiques</h4><div class="practical-grid"><div><small>QUARTIER À VISER</small><b>${cfg.area}</b></div><div><small>MÉTÉO PROBABLE</small><b>${cfg.weather}</b></div><div><small>MONNAIE</small><b>${cfg.currency}</b></div><div><small>NIVEAU DE GALÈRE</small><b>${cfg.pain}</b></div></div><div class="practical-transfer"><b>Transfert :</b> ${cfg.transfer}</div></section>`}
function css(){const s=document.createElement('style');s.textContent=`.retro-extra{padding:0 22px 22px;display:grid;grid-template-columns:1.35fr .9fr;gap:18px}.retro-travel{grid-column:1/-1;background:#164b3c;color:#fff;padding:18px}.retro-travel h4,.retro-budget h4,.retro-practical h4{font:900 24px Georgia,serif;margin:0 0 8px}.retro-intro{margin:0 0 14px;font-size:13px}.retro-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.retro-grid>div{background:#fff;color:#111;padding:11px;min-height:66px}.retro-grid small,.practical-grid small{display:block;font-size:9px;font-weight:900;letter-spacing:.04em;color:#776c5e}.retro-grid b{display:block;font-size:14px;margin-top:3px}.retro-grid span{display:block;font-size:9px;color:#756b5e;margin-top:4px}.retro-note{margin-top:9px;background:#f0d77a;color:#2e281f;padding:8px 10px;font-size:11px;font-weight:800}.retro-budget,.retro-practical{background:#fffaf2;border:1px solid #ded2bf;padding:16px}.budget-row{display:flex;justify-content:space-between;gap:16px;padding:8px 0;border-bottom:1px dashed #d8cbb8}.budget-row.total{border-top:2px solid #222;border-bottom:0;margin-top:5px;padding-top:11px;font-size:17px}.retro-budget p{font-size:10px;color:#756b5e;line-height:1.45}.practical-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.practical-grid>div{background:#f5eee3;padding:10px}.practical-grid b{display:block;margin-top:3px}.practical-transfer{margin-top:10px;font-size:11px;line-height:1.45}@media(max-width:760px){.retro-extra{grid-template-columns:1fr}.retro-grid{grid-template-columns:1fr}.retro-travel{grid-column:auto}.practical-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
async function run(){css();let data={};try{const r=await fetch(`flights-live.json?ts=${Date.now()}`,{cache:'no-store'});if(r.ok)data=await r.json()}catch(e){}document.querySelectorAll('.current-card').forEach(card=>{const btn=card.querySelector('[data-current-vote]');const id=btn?.dataset.currentVote;const cfg=INFO[id];if(!cfg||card.querySelector('.retro-extra'))return;const live=liveFor(data,id);if(live?.price>CAP)return;const extra=document.createElement('div');extra.className='retro-extra';extra.innerHTML=travelBlock(id,cfg,live)+budgetBlock(cfg,live)+practicalBlock(cfg);const actions=card.querySelector('.current-actions');card.insertBefore(extra,actions);});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(run,260));else setTimeout(run,260);
})();