(()=>{
const MAX=250;
const RADAR=[
{id:'liverpool',flag:'🇬🇧',name:'Liverpool',mode:'flight',onSite:[295,445],note:'Direct vérifié, mais le transport actuel est trop cher pour la shortlist.'},
{id:'valencia',flag:'🇪🇸',name:'Valence',mode:'flight',onSite:[270,385],note:'Bon temps utile ; le total n’est plus une option cheap.'},
{id:'belgrade',flag:'🇷🇸',name:'Belgrade',mode:'flight',onSite:[203,310],note:'Vie locale accessible, mais le vol direct pèse lourd.'},
{id:'sarajevo',flag:'🇧🇦',name:'Sarajevo',mode:'flight',onSite:[178,280],note:'Aller séduisant, retour direct du dimanche non confirmé.'},
{id:'amsterdam',flag:'🇳🇱',name:'Amsterdam',mode:'train',onSite:[375,545],note:'Très simple en train, rarement économique à onze.'},
{id:'malaga',flag:'🇪🇸',name:'Málaga',mode:'flight',onSite:[215,305],note:'Billet bas, mais seulement ~36 h utiles dans le snapshot.'},
{id:'alicante',flag:'🇪🇸',name:'Alicante',mode:'flight',onSite:[205,285],note:'Équilibre correct et environ 50 h utiles.'},
{id:'seville',flag:'🇪🇸',name:'Séville',mode:'flight',onSite:[225,315],note:'Très belle option, mais total actuel élevé.'},
{id:'munich',flag:'🇩🇪',name:'Munich',mode:'flight',onSite:[300,420],note:'Brasseries oui, Oktoberfest non sur ce week-end.'},
{id:'milan',flag:'🇮🇹',name:'Milan',mode:'flight',onSite:[300,420],note:'Beaucoup de directs ; prix du 23→25 à vérifier.'},
{id:'bilbao',flag:'🇪🇸',name:'Bilbao',mode:'flight',onSite:[250,340],note:'Compacte et excellente côté bouffe ; direct à vérifier.'},
{id:'naples',flag:'🇮🇹',name:'Naples',mode:'flight',onSite:[215,305],note:'Expérience très forte, total actuel au-dessus de Bologne.'},
{id:'turin',flag:'🇮🇹',name:'Turin',mode:'train',onSite:[240,330],note:'Alternative italienne ; trajet réellement exploitable à vérifier.'}
];
const €=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
const range=r=>`${€(r[0])}–${€(r[1])}`;
const hours=n=>n==null?'—':`${Math.floor(n)} h ${String(Math.round((n%1)*60)).padStart(2,'0')}`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function live(snapshot,id){const c=snapshot?.cities?.[id];return c?.options?.find(x=>x.kind==='recommended')||c?.options?.[0]||null}
function booking(c){return c.mode==='train'?'https://www.sncf-connect.com/':`https://www.google.com/travel/flights?q=${encodeURIComponent(`Flights from Paris to ${c.name} on 2026-10-23 returning 2026-10-25`)}`}
function renderQuick(c,m){document.querySelector('#cityList').innerHTML=`<article class="selection-card is-eligible" id="fiche-${c.id}"><header class="selection-card-head"><div><span class="city-label">${c.flag} Candidate sous 250 €</span><h3>${esc(c.name)}</h3></div><div class="vote-state vote-state-eligible"><b>Éligible au vote</b><span>${€(m.price)} A/R · sous le plafond</span></div></header><p class="selection-summary">${esc(c.note)}</p><div class="decision-metrics"><div><small>${c.mode==='train'?'🚄 Train':'✈️ Vol direct'}</small><b>${€(m.price)}</b></div><div><small>🧾 Budget sur place</small><b>${range(c.onSite)}</b></div><div><small>💰 Total réaliste</small><b>${range([m.price+c.onSite[0],m.price+c.onSite[1]])}</b></div><div><small>⏱️ Temps utile</small><b>${hours(m.usefulHours)}</b></div></div><div class="route-panel"><div><small>Règle appliquée automatiquement</small><b>Transport vérifié ≤ 250 € : cette ville appartient au carrousel, pas au tableau.</b></div><a href="${booking(c)}" target="_blank" rel="noopener">Vérifier le trajet ↗</a></div><footer class="card-footer"><div></div><div class="actions"><button class="vote-btn" id="quickVote-${c.id}">Je vote ${esc(c.name)}</button></div></footer></article>`;
const btn=document.querySelector(`#quickVote-${c.id}`);if(btn)btn.onclick=async()=>{const who=document.querySelector('#whoSelect')?.value;if(!who){alert('Choisis d’abord ton prénom.');return}localStorage.setItem(`petitschats-destination-${who}`,c.id);try{await fetch('/api/votes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({participant:who,city:c.id,category:'destination',choiceId:'phase1-destination',vote:'oui'})});btn.classList.add('on');btn.textContent=`Vote enregistré · ${c.name}`}catch(e){alert('Vote non enregistré, réessaie.')}}}
async function apply(){let snapshot;try{snapshot=await fetch(`flights-live.json?ts=${Date.now()}`,{cache:'no-store'}).then(r=>r.json())}catch(e){return}
const eligible=[],impossible=[];for(const c of RADAR){const o=live(snapshot,c.id),price=o?.price??null;if(price!=null&&price<=MAX)eligible.push({c,m:{price,usefulHours:o?.usefulHours??null}});else impossible.push({c,m:{price,usefulHours:o?.usefulHours??null}})}
const carousel=document.querySelector('#destinationJump');const picker=document.querySelector('#cityPicker');if(carousel){for(const {c,m} of eligible){if(carousel.querySelector(`[data-radar-city="${c.id}"]`))continue;const b=document.createElement('button');b.type='button';b.className='destination-card is-eligible';b.dataset.radarCity=c.id;b.innerHTML=`<span class="destination-card-photo" style="display:grid;place-items:center;font-size:56px;background:#eef3ee">${c.flag}</span><span class="destination-card-body"><span class="destination-card-kicker">${c.flag} Candidate automatique</span><strong>${esc(c.name)}</strong><span class="destination-card-status">Éligible au vote</span><span class="destination-card-metrics"><span><small>Transport</small><b>${€(m.price)}</b></span><span><small>Sur place</small><b>${range(c.onSite)}</b></span><span><small>Total</small><b>${range([m.price+c.onSite[0],m.price+c.onSite[1]])}</b></span><span><small>Temps utile</small><b>${hours(m.usefulHours)}</b></span></span><span class="destination-card-open">Voir la fiche <i>→</i></span></span>`;b.onclick=()=>renderQuick(c,m);carousel.appendChild(b);if(picker&&!Array.from(picker.options).some(o=>o.value===c.id)){const opt=new Option(`${c.flag} ${c.name}`,c.id);picker.add(opt)}}}
const body=document.querySelector('#compareBody');if(body){for(const {c,m} of impossible){if(body.querySelector(`[data-extra-city="${c.id}"]`))continue;const tr=document.createElement('tr');tr.dataset.extraCity=c.id;const total=m.price==null?null:[m.price+c.onSite[0],m.price+c.onSite[1]];tr.innerHTML=`<td><b>${c.flag} ${esc(c.name)}</b><small>Candidate contrôlée</small></td><td class="price ${m.price==null?'verify':''}">${m.price==null?'À vérifier':`${€(m.price)}*`}<small>${c.mode==='train'?'Train A/R direct':'Vols A/R directs'}</small></td><td class="price">${range(c.onSite)}</td><td class="price ${total?'':'verify'}">${total?range(total):'À vérifier'}</td><td>${hours(m.usefulHours)}</td><td>—</td><td><span class="table-vote table-vote-${m.price!=null&&m.price>MAX?'excluded':'pending'}">${m.price!=null&&m.price>MAX?'Hors budget':'À vérifier'}</span><small>${esc(c.note)}</small></td><td><a class="book-link" href="${booking(c)}" target="_blank" rel="noopener">Contrôler ↗</a></td>`;body.appendChild(tr)}}
const count=document.querySelector('#carouselCount');if(count){const base=carousel?.querySelectorAll('.destination-card:not([data-radar-city])').length||0;count.textContent=`${base+eligible.length} destinations sous 250 € A/R · toutes dans ce carrousel.`}
const summary=document.querySelector('#eligibilitySummary');if(summary){const current=summary.querySelector('div:first-child span')?.textContent||'';const extras=eligible.map(x=>`${x.c.flag} ${x.c.name}`).join(' · ');if(extras&&!current.includes(eligible[0].c.name))summary.querySelector('div:first-child span').textContent=[current,extras].filter(Boolean).join(' · ')}
}
window.addEventListener('load',()=>setTimeout(apply,700));
})();