(()=>{
const ACTION='https://github.com/plero75/mobili/actions/workflows/update-trip-flights.yml';
const LABELS={recommended:'⭐ Meilleur compromis',cheapest:'💸 Le moins cher',max_weekend:'⏱️ Max de week-end'};
const cityAliases={dublin:'Dublin',liverpool:'Liverpool',krakow:'Cracovie',valencia:'Valence',belgrade:'Belgrade',sarajevo:'Sarajevo'};
const fmtMoney=(n,c='EUR')=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:c,maximumFractionDigits:0}).format(n);
const hhmm=s=>{if(!s)return'—';const d=new Date(s);return Number.isNaN(d.getTime())?String(s).slice(11,16):d.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})};
const hours=h=>{if(h==null)return'—';const m=Math.round(h*60),hh=Math.floor(m/60),mm=m%60;return `${hh} h${mm?` ${String(mm).padStart(2,'0')}`:''}`};
function style(){const s=document.createElement('style');s.textContent=`
.live-head{display:flex;gap:12px;align-items:center;justify-content:space-between;flex-wrap:wrap;margin:0 0 16px;padding:13px 15px;background:#fff4d8;border:1px solid #e1c573;color:#332817}.live-head b{font-family:Georgia,serif}.live-head small{display:block;color:#71695d;margin-top:3px;line-height:1.35}.refresh-link{display:inline-flex;align-items:center;gap:6px;padding:9px 11px;background:#173f32;color:#fff!important;text-decoration:none;font-size:12px;font-weight:950}.live-options{display:grid;gap:8px;margin:12px 0}.live-option{background:#fff;border:1px solid #d8ccb8;color:#27231d;padding:12px 13px}.live-option-top{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:7px}.live-option-top b:first-child{font-size:13px}.live-price{font:900 18px Georgia,serif;color:#173f32}.live-route{font-weight:900;font-size:13px;line-height:1.35}.live-meta{font-size:11px;color:#71695d;line-height:1.45;margin-top:5px}.live-price-note{font-size:10px;color:#8d4037;line-height:1.35;margin-top:7px}.live-useful{display:inline-block;margin-top:7px;background:#e7f0e8;padding:5px 7px;font-weight:900;font-size:11px}.live-warning{display:inline-block;margin-top:7px;margin-left:6px;background:#ffe5d8;color:#8d321f;padding:5px 7px;font-weight:900;font-size:11px}.live-stale{background:#fae9e2!important}.live-empty{font-size:12px;color:#71695d;padding:10px 0}.compare .live-mini{display:block;font-size:10px;color:#71695d;margin-top:4px;line-height:1.25}.compare .live-price-table{font-weight:950;color:#173f32}.live-global{margin:0 0 20px}@media(max-width:760px){.live-option-top{align-items:flex-start}.live-price{white-space:nowrap}}
`;document.head.appendChild(s)}
function optionHTML(o){const out=o.outbound||{},back=o.return||{};const early=o.earlyReturn||((o.leaveCenter||'').slice(11,16)<'08:00');return `<div class="live-option"><div class="live-option-top"><b>${LABELS[o.kind]||'Option'}</b><span class="live-price">${fmtMoney(o.price,o.currency||'EUR')}</span></div><div class="live-route">${out.carrier||''} · ${out.from||'?'} ${hhmm(out.departure)} → ${out.to||'?'} ${hhmm(out.arrival)}${out.stops?` · ${out.stops} esc.`:' · direct'}</div><div class="live-route" style="margin-top:4px">Retour · ${back.carrier||''} · ${back.from||'?'} ${hhmm(back.departure)} → ${back.to||'?'} ${hhmm(back.arrival)}${back.stops?` · ${back.stops} esc.`:' · direct'}</div><div class="live-meta">Dans le centre vers <b>${hhmm(o.centerArrival)}</b> · départ conseillé du centre dimanche vers <b>${hhmm(o.leaveCenter)}</b></div><span class="live-useful">Temps utile ≈ ${hours(o.usefulHours)}</span>${early?'<span class="live-warning">⚠️ retour très matinal</span>':''}${o.priceNote?`<div class="live-price-note">* ${o.priceNote}</div>`:''}</div>`}
function cardBlock(cityData){if(!cityData||!cityData.options?.length)return `<div class="live-empty">Actualisation live indisponible pour cette ville : les horaires statiques et le lien Google Flights restent utilisables.</div>`;return `<div class="live-options">${cityData.options.map(optionHTML).join('')}</div>`}
function injectCards(data){document.querySelectorAll('.identity[data-city]').forEach(card=>{const id=card.dataset.city,d=data.cities?.[id];if(!d)return;const focus=card.querySelector('.transport-focus');if(!focus||focus.querySelector('.live-options'))return;const links=focus.querySelector('.transport-links');const box=document.createElement('div');box.innerHTML=cardBlock(d);while(box.firstChild)focus.insertBefore(box.firstChild,links||null);const cells=focus.querySelectorAll('.transport-cell');const rec=d.options?.find(x=>x.kind==='recommended')||d.options?.[0];if(rec&&cells.length>=6){cells[5].innerHTML=`<small>Prix actualisé</small><b class="transport-live">${fmtMoney(rec.price,rec.currency||'EUR')}*</b><span class="gf-note">${d.stale?'Dernier résultat valide':'snapshot Google Flights'}</span>`}}
)}
function updateTable(data){const rows=[...document.querySelectorAll('#comparatif .compare tbody tr')];rows.forEach(r=>{const txt=(r.querySelector('td')?.textContent||'').toLowerCase();const id=Object.keys(cityAliases).find(k=>txt.includes(cityAliases[k].toLowerCase()));if(!id)return;const d=data.cities?.[id],rec=d?.options?.find(x=>x.kind==='recommended')||d?.options?.[0];if(!rec)return;const tds=r.querySelectorAll('td');if(tds.length>=10){tds[6].innerHTML=`<b>${hours(rec.usefulHours)}</b><span class="live-mini">centre ven. ${hhmm(rec.centerArrival)} → départ centre dim. ${hhmm(rec.leaveCenter)}</span>`;tds[7].innerHTML=`<span class="live-price-table">${fmtMoney(rec.price,rec.currency||'EUR')}*</span><span class="live-mini">${d.stale?'dernier snapshot valide':'Google Flights · actualisé'}</span>`}})}
function globalHead(data){const target=document.querySelector('#comparatif .compare');if(!target||document.querySelector('.live-global'))return;const div=document.createElement('div');div.className='live-head live-global'+(data.successfulCities?'':' live-stale');const when=data.generatedAt?new Date(data.generatedAt).toLocaleString('fr-FR',{dateStyle:'short',timeStyle:'short'}):'pas encore exécutée';const disclaimer=data.priceDisclaimer||'Prix indicatifs à revérifier avant achat.';div.innerHTML=`<div><b>✈️ Prix & horaires Google Flights actualisés</b><small>Dernier refresh : ${when} · ${data.successfulCities||0}/6 destinations aériennes mises à jour.<br>* ${disclaimer}</small></div><a class="refresh-link" href="${ACTION}" target="_blank" rel="noopener">↻ Actualiser maintenant</a>`;target.parentNode.insertBefore(div,target)}
async function run(){style();try{const r=await fetch(`flights-live.json?ts=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json();globalHead(data);injectCards(data);updateTable(data)}catch(e){console.warn('Live flights unavailable',e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(run,80));else setTimeout(run,80);
})();