(()=>{
const CAP=200;
const SHORTLIST=[
{id:'krakow',name:'Cracovie',flag:'🇵🇱',mode:'✈️ direct',stay:[255,305],pain:'Beauvais peut grignoter du confort.'},
{id:'dublin',name:'Dublin',flag:'🇮🇪',mode:'✈️ direct',stay:[350,430],pain:'Hébergement cher et marathon le dimanche.'},
{id:'bologna',name:'Bologne',flag:'🇮🇹',mode:'✈️ direct',stay:[285,335],pain:'Moins “grande capitale”, tout repose sur l’ambiance et la bouffe.'},
{id:'tirana',name:'Tirana',flag:'🇦🇱',mode:'✈️ direct',transportEstimate:[120,190],stay:[210,260],pain:'Vol exact 23–25 octobre encore à verrouiller.'},
{id:'prague',name:'Prague',flag:'🇨🇿',mode:'✈️ direct',stay:[260,310],pain:'Très forte candidate, mais sortie si le direct dépasse 200 €.'},
{id:'vienna',name:'Vienne',flag:'🇦🇹',mode:'✈️ direct',transportEstimate:[150,200],stay:[315,370],pain:'Plus chère sur place que les options d’Europe de l’Est.'},
{id:'rotterdam',name:'Rotterdam',flag:'🇳🇱',mode:'🚄 direct',transportEstimate:[100,180],stay:[330,385],pain:'Hôtels néerlandais chers et ville moins carte-postale.'},
{id:'london',name:'Londres',flag:'🇬🇧',mode:'🚄 direct',transportEstimate:[250,320],stay:[420,500],pain:'Le transport dépasse notre règle des 200 €.'},
{id:'bucharest',name:'Bucarest',flag:'🇷🇴',mode:'✈️ direct',transportEstimate:[160,200],stay:[225,275],pain:'Le direct exact doit rester sous le plafond.'},
{id:'munich',name:'Munich',flag:'🇩🇪',mode:'✈️ direct',transportEstimate:[170,200],stay:[325,380],pain:'Pas d’Oktoberfest à ces dates et budget plus élevé.'},
{id:'turin',name:'Turin',flag:'🇮🇹',mode:'🚄 / ✈️ direct',transportEstimate:[150,200],stay:[275,330],pain:'Le bon couple prix + horaires n’est pas encore verrouillé.'},
{id:'amsterdam',name:'Amsterdam',flag:'🇳🇱',mode:'🚄 direct',transportEstimate:[120,190],stay:[360,430],pain:'Le logement pour 11 peut faire exploser le total.'},
{id:'malaga',name:'Málaga',flag:'🇪🇸',mode:'✈️ direct',stay:[270,325],pain:'Les horaires peuvent réduire fortement le week-end.'},
{id:'alicante',name:'Alicante',flag:'🇪🇸',mode:'✈️ direct',stay:[255,310],pain:'Moins “événement” que certaines concurrentes.'}
];
const fmt=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
const hh=s=>s?String(s).slice(11,16):'—';
const mid=r=>Math.round((r[0]+r[1])/2/5)*5;
const spread=r=>`${fmt(r[0])}–${fmt(r[1])}`;
function liveFor(data,id){
 const c=data?.cities?.[id]; const o=c?.options?.find(x=>x.kind==='recommended')||c?.options?.[0];
 if(o)return {price:o.price,useful:o.usefulHours,route:`${o.outbound.from} ${hh(o.outbound.departure)} → ${o.outbound.to} ${hh(o.outbound.arrival)} · retour ${hh(o.return.departure)}`,kind:'verified'};
 const d=(data?.dealScout?.candidates||[]).find(x=>x.id===id);
 if(d)return {price:d.flightPrice,useful:d.usefulHours,route:`${d.outbound.from} ${hh(d.outbound.departure)} → ${d.outbound.to} ${hh(d.outbound.arrival)} · retour ${hh(d.return.departure)}`,kind:'verified'};
 return null;
}
function enrich(data){return SHORTLIST.map(x=>{const live=liveFor(data,x.id);const tr=live?{min:live.price,max:live.price,label:fmt(live.price),kind:'verified'}:(x.transportEstimate?{min:x.transportEstimate[0],max:x.transportEstimate[1],label:`≈ ${fmt(mid(x.transportEstimate))}`,kind:'estimated'}:null);const total=tr?[tr.min+x.stay[0],tr.max+x.stay[1]]:null;return {...x,live,tr,total}})}
function eligible(rows){return rows.filter(x=>x.tr&&x.tr.max<=CAP)}
function hassle(x){if(x.mode.includes('🚄'))return {txt:'🟢 Facile',cls:'easy'};if(!x.live)return {txt:'🟡 Un petit effort',cls:'medium'};if(x.live.useful<40||x.live.route.includes('BVA'))return {txt:'🔴 Expédition du Hobbit',cls:'hard'};return {txt:'🟡 Un petit effort',cls:'medium'}}
function awards(rows){const o={};const put=(x,t)=>{if(x)o[x.id]=[...(o[x.id]||[]),t]};put([...rows].sort((a,b)=>a.tr.min-b.tr.min)[0],'💸 moins cher');put([...rows].filter(x=>x.total).sort((a,b)=>mid(a.total)-mid(b.total))[0],'🏆 choix rationnel');put([...rows].filter(x=>x.live?.useful!=null).sort((a,b)=>b.live.useful-a.live.useful)[0],'⏱ plus de week-end');return o}
function recommendation(rows){const rational=[...rows].filter(x=>x.total).sort((a,b)=>(mid(a.total)+(50-(a.live?.useful||42))*6)-(mid(b.total)+(50-(b.live?.useful||42))*6))[0];const pleasure=[...rows].filter(x=>['dublin','bologna','krakow','tirana'].includes(x.id)).sort((a,b)=>(b.live?.useful||45)-(a.live?.useful||45))[0]||rows[0];return {rational,pleasure}}
async function vote(id,name){const who=localStorage.getItem('petitschats-name')||'';if(!who){document.querySelector('#who')?.scrollIntoView({behavior:'smooth'});alert('Choisis d’abord ton prénom pour voter.');return}localStorage.setItem('petitschats-destination-'+who,id);try{await fetch('/api/votes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({participant:who,city:id,category:'destination',choiceId:'phase1-destination',vote:'oui'})})}catch(e){}document.querySelectorAll('[data-quick-vote]').forEach(b=>b.classList.toggle('picked',b.dataset.quickVote===id));}
function css(){const s=document.createElement('style');s.textContent=`
.shortlist-wrap{margin:10px 0 38px}.shortlist-head{margin-bottom:14px}.shortlist-head h2{font:900 38px Georgia,serif;margin:0}.shortlist-head p{max-width:760px;color:#665d51;margin:6px 0}.decision-table{overflow:auto;border:1px solid #d8ccb8;background:#fff;box-shadow:0 12px 36px #513b2212}.decision-table table{width:100%;border-collapse:collapse;min-width:900px}.decision-table th{background:#173f32;color:#fff;text-align:left;padding:11px 13px;font-size:11px;text-transform:uppercase;letter-spacing:.03em}.decision-table td{padding:15px 13px;border-bottom:1px solid #eee4d7;vertical-align:middle}.decision-city{font:900 19px Georgia,serif;color:#173f32}.decision-mode,.decision-sub{font-size:10px;color:#7d7163;margin-top:3px}.decision-main{font-weight:950;font-size:20px;color:#173f32}.decision-badges{display:flex;gap:4px;flex-wrap:wrap;margin-top:5px}.decision-badge{font-size:9px;font-weight:950;background:#fff0b7;padding:4px 6px}.decision-pain{font-size:11px;line-height:1.35;color:#745f4e;max-width:190px}.hassle{font-size:10px;font-weight:900;white-space:nowrap}.quick-vote{border:0;background:#173f32;color:white;font-weight:900;padding:9px 11px;cursor:pointer;border-radius:2px}.quick-vote.picked{background:#b83c67}.decision-foot{font-size:10px;color:#766c5f;margin-top:9px;line-height:1.45}.decision-rec{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:14px}.rec-card{background:#f7f1e8;border:1px solid #e2d5c3;padding:13px}.rec-card b{display:block;color:#173f32;font-size:15px;margin-top:3px}@media(max-width:760px){.decision-rec{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
function render(rows,excluded,data){const a=awards(rows),rec=recommendation(rows);const checked=data?.generatedAt?new Date(data.generatedAt).toLocaleString('fr-FR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'dernier relevé disponible';return `<div class="w shortlist-wrap"><div class="shortlist-head"><div class="script">Le Tinder des week-ends</div><h2>Prix. Budget. Vrai temps sur place.</h2><p>C’est tout ce qu’il faut pour le premier choix. Le temps de week-end correspond à <b>l’arrivée en centre-ville → le moment où il faut quitter le centre</b>, après transferts et marge aéroport.</p></div><div class="decision-table"><table><thead><tr><th>Destination</th><th>Transport A/R</th><th>Budget global</th><th>Temps de week-end</th><th>Galère</th><th>Pourquoi on peut regretter</th><th></th></tr></thead><tbody>${rows.map(x=>{const h=hassle(x);return `<tr><td><div class="decision-city">${x.flag} ${x.name}</div><div class="decision-mode">${x.mode}</div><div class="decision-badges">${(a[x.id]||[]).map(t=>`<span class="decision-badge">${t}</span>`).join('')}</div></td><td><div class="decision-main">${x.tr.label}</div><div class="decision-sub">${x.tr.kind==='verified'?'Prix vérifié':'Prix estimatif'}${x.live?.route?` · ${x.live.route}`:''}</div></td><td><div class="decision-main">≈ ${fmt(mid(x.total))}</div><div class="decision-sub">fourchette ${spread(x.total)}</div></td><td>${x.live?.useful!=null?`<div class="decision-main">≈ ${Math.round(x.live.useful)} h</div><div class="decision-sub">après transferts / marge départ</div>`:`<div class="decision-main">à confirmer</div><div class="decision-sub">horaires exacts nécessaires</div>`}</td><td><span class="hassle ${h.cls}">${h.txt}</span></td><td><div class="decision-pain">${x.pain}</div></td><td><button class="quick-vote" data-quick-vote="${x.id}" data-name="${x.name}">❤️ Voter</button></td></tr>`}).join('')}</tbody></table></div><div class="decision-foot">Règle éliminatoire : <b>transport A/R ≤ 200 € / personne</b>. Prix vérifiés : ${checked}. Les estimations sont clairement marquées comme telles.${excluded.length?` Hors sélection actuellement : ${excluded.filter(x=>x.tr).map(x=>x.name).join(', ')}.`:''}</div>${rec.rational&&rec.pleasure?`<div class="decision-rec"><div class="rec-card">🧠 Notre choix rationnel<b>${rec.rational.flag} ${rec.rational.name}</b><span>Meilleur compromis coût total + temps de week-end.</span></div><div class="rec-card">❤️ Notre choix plaisir<b>${rec.pleasure.flag} ${rec.pleasure.name}</b><span>Celui qu’on choisirait pour l’expérience de groupe, même s’il n’est pas premier sur Excel.</span></div></div>`:''}</div>`}
async function run(){css();let data={};try{const r=await fetch(`flights-live.json?ts=${Date.now()}`,{cache:'no-store'});if(r.ok)data=await r.json()}catch(e){}const all=enrich(data),rows=eligible(all),excluded=all.filter(x=>!rows.includes(x));const old=document.querySelector('#shortlist');if(old)old.remove();const section=document.createElement('section');section.id='shortlist';section.innerHTML=render(rows,excluded,data);const anchor=document.querySelector('#destinations');if(anchor)anchor.parentNode.insertBefore(section,anchor);document.querySelectorAll('[data-quick-vote]').forEach(b=>b.onclick=()=>vote(b.dataset.quickVote,b.dataset.name))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(run,70));else setTimeout(run,70);
})();