(()=>{
const TRAINS={
brussels:{name:'Bruxelles',operator:'Eurostar',route:'Paris-Nord → Bruxelles-Midi',duration:'≈ 1 h 22',out:'23/10 · horaire exact à confirmer',back:'25/10 · horaire exact à confirmer',fare:'dès 58 € A/R',note:'Tarif officiel à partir de 29 € par trajet ; panier daté du week-end à revérifier.',url:'https://www.eurostar.com/fr-fr/train/paris-bruxelles'},
rotterdam:{name:'Rotterdam',operator:'Eurostar',route:'Paris-Nord → Rotterdam Centraal',duration:'≈ 2 h 37',out:'23/10 · horaire exact à confirmer',back:'25/10 · horaire exact à confirmer',fare:'dès 70 € A/R',note:'Tarif officiel à partir de 35 € par trajet ; panier daté du week-end à revérifier.',url:'https://www.eurostar.com/fr-fr/train/paris-rotterdam'},
london:{name:'Londres',operator:'Eurostar',route:'Paris-Nord → London St Pancras',duration:'≈ 2 h 17',out:'23/10 · horaire exact à confirmer',back:'25/10 · horaire exact à confirmer',fare:'dès 88 € A/R',note:'Tarif officiel à partir de 44 € par trajet ; passeport et ETA à prévoir.',url:'https://www.eurostar.com/fr-fr/train/paris-londres'},
amsterdam:{name:'Amsterdam',operator:'Eurostar',route:'Paris-Nord → Amsterdam Centraal',duration:'≈ 3 h 20–3 h 35',out:'23/10 · directs à sélectionner',back:'25/10 · directs à sélectionner',fare:'dès 70 € A/R',note:'Tarif officiel à partir de 35 € par trajet. Desserte directe observée : 16:18 → 19:50.',url:'https://www.eurostar.com/fr-fr/train/paris-amsterdam'},
turin:{name:'Turin',operator:'SNCF Connect / Trenitalia',route:'Paris → Torino Porta Susa',duration:'≈ 5 h 40+',out:'23/10 · à confirmer',back:'25/10 · à confirmer',fare:'À vérifier',note:'Option ferroviaire à comparer au vol ; tarif A/R et temps utile à verrouiller.',url:'https://www.sncf-connect.com/'}
};
function findData(el){const id=(el.id||'').replace('fiche-','');if(TRAINS[id])return TRAINS[id];const t=(el.textContent||'').toLowerCase();return Object.values(TRAINS).find(d=>t.includes(d.name.toLowerCase()));}
function block(d){return `<div class="train-inline"><div class="train-inline-title"><span>🚆 ${d.operator}</span><b>${d.fare}</b></div><strong>${d.route}</strong><div class="train-inline-grid"><div><small>Aller ven. 23/10</small>${d.out}</div><div><small>Retour dim. 25/10</small>${d.back}</div><div><small>Durée</small>${d.duration}</div></div><p>${d.note}</p><a href="${d.url}" target="_blank" rel="noopener">Voir horaires et tarifs →</a></div>`}
function patch(){document.querySelectorAll('.selection-card[id^="fiche-"]').forEach(card=>{const d=findData(card);if(!d)return;const old=card.querySelector('.train-inline');if(old)old.remove();const footer=card.querySelector('.card-footer');const holder=document.createElement('div');holder.innerHTML=block(d);if(footer)footer.before(holder.firstElementChild);else card.appendChild(holder.firstElementChild)});document.querySelectorAll('#compareBody tr').forEach(tr=>{const d=findData(tr);if(!d)return;const c=tr.children[1];if(!c||c.querySelector('.train-table-line'))return;const x=document.createElement('span');x.className='train-table-line';x.innerHTML=`<b>🚆 ${d.operator}</b><br>${d.route}<br>Aller : ${d.out}<br>Retour : ${d.back}<br>${d.duration} · ${d.fare}`;c.appendChild(x);const a=tr.querySelector('a.book-link');if(a){a.href=d.url;a.textContent='Voir train ↗'}})}
const css=document.createElement('style');css.textContent='.train-inline{margin:18px 24px 22px;padding:16px;border:1px solid #cfd8d1;background:#f6f8f5}.train-inline-title{display:flex;justify-content:space-between;gap:12px;margin-bottom:8px;color:#173f32}.train-inline-title span{font-weight:900}.train-inline-title b{color:#8b5600}.train-inline-grid{display:grid;grid-template-columns:1fr 1fr .7fr;gap:8px;margin-top:12px}.train-inline-grid>div{background:#fff;border:1px solid #dde3de;padding:10px;font-weight:800}.train-inline-grid small{display:block;text-transform:uppercase;font-size:10px;color:#6d746f;margin-bottom:4px}.train-inline p{font-size:11px;color:#687069}.train-inline a{display:inline-block;background:#164b38;color:#fff!important;padding:8px 10px;text-decoration:none;font-size:12px;font-weight:900}.train-table-line{display:block;margin-top:6px;font-size:11px;line-height:1.35;color:#5f685f}@media(max-width:760px){.train-inline{margin:14px 0}.train-inline-grid{grid-template-columns:1fr}}';document.head.appendChild(css);
window.addEventListener('load',()=>{patch();setTimeout(patch,500);setTimeout(patch,1500)});document.addEventListener('click',()=>setTimeout(patch,100));
})();
